"""Base común de personajes y atributos para la interfaz."""

ATRIBUTOS = [
    ("mujer", "¿El personaje es mujer?"),
    ("lentes", "¿El personaje usa lentes?"),
    ("sombrero", "¿El personaje usa sombrero?"),
    ("barba", "¿El personaje tiene barba?"),
    ("bigote", "¿Tiene bigote?"),
    ("cabello_negro", "¿Tiene el cabello negro?"),
    ("cabello_rubio", "¿Tiene el cabello rubio?"),
    ("cabello_rojo", "¿Tiene el cabello rojo?"),
    ("cabello_castano", "¿Tiene el cabello castaño?"),
    ("cabello_largo", "¿Tiene el cabello largo?"),
    ("ojos_claros", "¿Tiene los ojos claros?"),
    ("aretes", "¿Usa aretes?"),
]


PERSONAJES = [
    {"nombre": "Ana", "mujer": True, "lentes": False, "sombrero": False, "barba": False, "bigote": False,
     "cabello_negro": True, "cabello_rubio": False, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": True, "ojos_claros": False, "aretes": False},
    {"nombre": "Bruno", "mujer": False, "lentes": True, "sombrero": False, "barba": True, "bigote": True,
     "cabello_negro": True, "cabello_rubio": False, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": False, "ojos_claros": False, "aretes": False},
    {"nombre": "Carla", "mujer": True, "lentes": True, "sombrero": True, "barba": False, "bigote": False,
     "cabello_negro": False, "cabello_rubio": True, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": True, "ojos_claros": True, "aretes": False},
    {"nombre": "Diego", "mujer": False, "lentes": False, "sombrero": True, "barba": True, "bigote": True,
     "cabello_negro": False, "cabello_rubio": False, "cabello_rojo": True, "cabello_castano": False, "cabello_largo": False, "ojos_claros": True, "aretes": False},
    {"nombre": "Elena", "mujer": True, "lentes": True, "sombrero": False, "barba": False, "bigote": False,
     "cabello_negro": False, "cabello_rubio": False, "cabello_rojo": True, "cabello_castano": False, "cabello_largo": True, "ojos_claros": False, "aretes": False},
    {"nombre": "Fabio", "mujer": False, "lentes": False, "sombrero": False, "barba": True, "bigote": True,
     "cabello_negro": False, "cabello_rubio": True, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": False, "ojos_claros": True, "aretes": False},
    {"nombre": "Gabriela", "mujer": True, "lentes": False, "sombrero": True, "barba": False, "bigote": False,
     "cabello_negro": True, "cabello_rubio": False, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": True, "ojos_claros": False, "aretes": False},
    {"nombre": "Hugo", "mujer": False, "lentes": True, "sombrero": True, "barba": False, "bigote": False,
     "cabello_negro": False, "cabello_rubio": True, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": False, "ojos_claros": True, "aretes": False},
    {"nombre": "Irene", "mujer": True, "lentes": True, "sombrero": False, "barba": False, "bigote": False,
     "cabello_negro": True, "cabello_rubio": False, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": False, "ojos_claros": False, "aretes": False},
    {"nombre": "Javier", "mujer": False, "lentes": False, "sombrero": True, "barba": False, "bigote": False,
     "cabello_negro": True, "cabello_rubio": False, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": False, "ojos_claros": False, "aretes": False},
    {"nombre": "Karen", "mujer": True, "lentes": False, "sombrero": False, "barba": False, "bigote": False,
     "cabello_negro": False, "cabello_rubio": True, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": True, "ojos_claros": True, "aretes": False},
    {"nombre": "Luis", "mujer": False, "lentes": True, "sombrero": False, "barba": True, "bigote": True,
     "cabello_negro": False, "cabello_rubio": False, "cabello_rojo": True, "cabello_castano": False, "cabello_largo": False, "ojos_claros": False, "aretes": False},
    {"nombre": "Mateo", "mujer": False, "lentes": False, "sombrero": False, "barba": False, "bigote": True,
     "cabello_negro": False, "cabello_rubio": False, "cabello_rojo": False, "cabello_castano": True, "cabello_largo": False, "ojos_claros": False, "aretes": False},
    {"nombre": "Natalia", "mujer": True, "lentes": True, "sombrero": False, "barba": False, "bigote": False,
     "cabello_negro": False, "cabello_rubio": False, "cabello_rojo": False, "cabello_castano": True, "cabello_largo": True, "ojos_claros": True, "aretes": True},
    {"nombre": "Oscar", "mujer": False, "lentes": True, "sombrero": False, "barba": False, "bigote": False,
     "cabello_negro": True, "cabello_rubio": False, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": False, "ojos_claros": True, "aretes": False},
    {"nombre": "Paula", "mujer": True, "lentes": False, "sombrero": True, "barba": False, "bigote": False,
     "cabello_negro": False, "cabello_rubio": False, "cabello_rojo": True, "cabello_castano": False, "cabello_largo": False, "ojos_claros": True, "aretes": True},
    {"nombre": "Rafael", "mujer": False, "lentes": False, "sombrero": True, "barba": True, "bigote": False,
     "cabello_negro": False, "cabello_rubio": False, "cabello_rojo": False, "cabello_castano": True, "cabello_largo": False, "ojos_claros": False, "aretes": False},
    {"nombre": "Sofia", "mujer": True, "lentes": True, "sombrero": False, "barba": False, "bigote": False,
     "cabello_negro": False, "cabello_rubio": True, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": False, "ojos_claros": False, "aretes": True},
    {"nombre": "Tomas", "mujer": False, "lentes": False, "sombrero": False, "barba": False, "bigote": False,
     "cabello_negro": False, "cabello_rubio": True, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": True, "ojos_claros": True, "aretes": False},
    {"nombre": "Valeria", "mujer": True, "lentes": False, "sombrero": False, "barba": False, "bigote": False,
     "cabello_negro": False, "cabello_rubio": False, "cabello_rojo": False, "cabello_castano": True, "cabello_largo": True, "ojos_claros": False, "aretes": True},
    {"nombre": "Walter", "mujer": False, "lentes": True, "sombrero": True, "barba": True, "bigote": True,
     "cabello_negro": True, "cabello_rubio": False, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": False, "ojos_claros": True, "aretes": False},
    {"nombre": "Ximena", "mujer": True, "lentes": True, "sombrero": True, "barba": False, "bigote": False,
     "cabello_negro": True, "cabello_rubio": False, "cabello_rojo": False, "cabello_castano": False, "cabello_largo": True, "ojos_claros": True, "aretes": True},
    {"nombre": "Yago", "mujer": False, "lentes": True, "sombrero": False, "barba": False, "bigote": False,
     "cabello_negro": False, "cabello_rubio": False, "cabello_rojo": True, "cabello_castano": False, "cabello_largo": False, "ojos_claros": True, "aretes": False},
    {"nombre": "Zoe", "mujer": True, "lentes": False, "sombrero": False, "barba": False, "bigote": False,
     "cabello_negro": False, "cabello_rubio": False, "cabello_rojo": True, "cabello_castano": False, "cabello_largo": True, "ojos_claros": True, "aretes": True},
]
